// <auto-generated />
using GeekShopping.UserAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.UserAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20231209032202_AddUser")]
    partial class AddUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.UserAPI.Model.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "Admin123%",
                            Role = "admin",
                            UserName = "welligton"
                        },
                        new
                        {
                            Id = 2L,
                            Password = "Joao123%",
                            Role = "client",
                            UserName = "joao"
                        },
                        new
                        {
                            Id = 3L,
                            Password = "Maria123%",
                            Role = "client",
                            UserName = "maria"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
