name: "microsservice"

on: 
  push:
    branches:
      - 'feature**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Run a one-line script     

  deploy-dev:
     runs-on: windows-latest
     environment: 
       name: Desenvolvimento
     needs: build
     steps:
      - name: Run a one-line script

  deploy-hmg:
     runs-on: windows-latest
     environment: 
       name: Homologacao
     needs: deploy-dev
     steps:
      - name: Run a one-line script

  deploy-pro:
     runs-on: windows-latest
     environment: 
       name: Producao
     needs:  deploy-hmg
     steps:
      - name: Run a one-line script

    
  
  
