name: "microsservice"

on: 
  push:
    branches:
      - 'feature**'

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Run a one-line script 
        uses: actions/checkout@v2

  desenvolvimento:
   runs-on: windows-latest  
   environment:
    name: Desenvolvimento
   steps:
      - name: Run a one-line script 
        uses: actions/checkout@v2

        
