name: "microsservice"

on: 
  push:
    branches:
      - 'feature**'

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Run a one-line script 
        uses: actions/checkout@v2

  desenvolvimento:
   runs-on: windows-latest  
   needs:
    - build
   environment:
    name: Desenvolvimento
   steps:
      - name: Run a one-line script 
        uses: actions/checkout@v2

  homologacao:
   runs-on: windows-latest  
   needs:
    - desenvolvimento
   environment:
    name: Homologacao
   steps:
      - name: Run a one-line script 
        uses: actions/checkout@v2

  producao:
   runs-on: windows-latest  
   needs:
    - homologacao
   environment:
    name: Producao
   steps:
      - name: Run a one-line script 
        uses: actions/checkout@v2      
